-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;



CREATE TABLE IF NOT EXISTS public.events
(
    id serial NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    event_type integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    deadline_date timestamp with time zone NOT NULL,
    expiry_date timestamp with time zone NOT NULL,
                             event_banner_url character varying(100) NOT NULL,
    participants_limit smallint,
    address_id integer,
    status integer NOT NULL,
    updated_at timestamp with time zone,
                             PRIMARY KEY (id)
    );



CREATE TABLE IF NOT EXISTS public.addresses
(
    id serial NOT NULL,
    street_name character varying(50) NOT NULL,
    house_number character varying(5) NOT NULL,
    postal_code character varying(5) NOT NULL,
    city character varying(50) NOT NULL,
    longitude numeric,
    latitude numeric,
    created_at timestamp with time zone NOT NULL default now(),
    updated_at timestamp with time zone,
                             PRIMARY KEY (id)
    );



CREATE TABLE IF NOT EXISTS public.participants
(
    id serial NOT NULL,
    created_at timestamp with time zone NOT NULL default now(),
    full_name character varying NOT NULL,
    email character varying(100) NOT NULL UNIQUE,
    mobile_no character varying(20),
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.event_participants
(
    id serial NOT NULL,
    created_at timestamp with time zone NOT NULL,
    event_id integer NOT NULL,
    participant_id integer NOT NULL,
    is_cancelled boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
    );



ALTER TABLE IF EXISTS public.events
DROP CONSTRAINT IF EXISTS address_fkey;
ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT address_fkey FOREIGN KEY (address_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;



ALTER TABLE IF EXISTS public.event_participants
DROP CONSTRAINT IF EXISTS events_fkey;
ALTER TABLE IF EXISTS public.event_participants
    ADD CONSTRAINT events_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event_participants
DROP CONSTRAINT IF EXISTS participants_fkey;
ALTER TABLE IF EXISTS public.event_participants
    ADD CONSTRAINT participants_fkey FOREIGN KEY (participant_id)
    REFERENCES public.participants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;